# Generated by Django 2.2 on 2020-06-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='helpfulness_score',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.FloatField(db_index=True),
        ),
    ]
